server:
  port: 38761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:38761/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000  
