server:
  port: 38801
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:38761/eureka/
spring:
  application:
    name: application-eureka-client-provider
management:
  endpoint:
    health:
      enabled: true
jungle:
  secret: yoyo ! Peppa Pig !
